### ISSUE TITLE
Can we send tokens array in the fcm.send() to send notifications to multiple devices 

### ISSUE THREAD

**Issue by LakshmiKalyani93** [smartnav/fcm-notification#1]

**Comment by smartnav** [comment]
Hi @LakshmiKalyani93 

You can use **Send to topic** for this.

_FCM topic messaging allows you to send a message to multiple devices that have opted in to a particular topic. But before this we need to subscribe to topic._

You can check this:
https://github.com/smartnav/fcm-notification#subscribe-to-topic

If you still have a confusion please let me know, I can make a function for you also.

Thanks.

**Comment by LakshmiKalyani93** [comment]
Hi Naveen,


Yes, can you please write me a function on that!


var FCM = new fcm('path/to/privatekey.json');


could you please tell me is it private key json we need use while preparing
or any server key required for that?



Thanks,
Kalyani

**Comment by smartnav** [comment]
Hi @LakshmiKalyani93
Sorry for late reply.

I have added the send to multiple token function. You can check from this link:
https://github.com/smartnav/fcm-notification#send-to-multiple-tokens

Only privatekey.json required from server end to send push notification. (Screen attached)

![](https://user-images.githubusercontent.com/19702085/46529601-a7390300-c8b4-11e8-9427-fe02505bea6b.gif "ddd")

Thanks
