### ISSUE TITLE
Icon Configuration

### ISSUE THREAD

**Issue by cirocsb10** [smartnav/fcm-notification#6]
Hi guys,
How to configure lib to send notification with icons?
Thanks for help

**Comment by smartnav** [comment]
Please check this link:

https://github.com/smartnav/fcm-notification#putting-it-all-together

**Comment by cirocsb10** [comment]
it is important to note that only this icon setting does not guarantee sending the notification to the device. it is necessary to declare the icon on the device with the same name as the indicated icon.
